from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
import random
import os
import time
import hashlib
from dotenv import load_dotenv
from mistralai.client import Mistral
from pydantic import BaseModel
from gtts import gTTS

env_path = os.path.join(os.path.dirname(__file__), '../.env')
load_dotenv(dotenv_path=env_path)
app = FastAPI()

# Mount audio directory to serve generated files
os.makedirs("audio", exist_ok=True)
app.mount("/audio", StaticFiles(directory="audio"), name="audio")

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:1111", 
        "http://localhost:3000", 
        "https://pinoyta-frontend.onrender.com"
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

MISTRAL_API_KEY = os.getenv("MISTRAL_API_KEY")

class VoiceMessage(BaseModel):
    id: str
    author: str
    role: str
    dialect: str
    time: str
    transcript: str
    verified: bool
    audioUrl: str | None = None

def generate_audio(text: str, author_id: str, lang: str = 'en') -> str:
    """Generate audio using gTTS and return the URL."""
    # Create a simple hash to cache the audio file based on text content
    text_hash = hashlib.md5(text.encode()).hexdigest()[:8]
    filename = f"{author_id}_{text_hash}.mp3"
    filepath = os.path.join("audio", filename)
    
    if not os.path.exists(filepath):
        try:
            # lang 'tl' for Tagalog/Bisaya simulation, 'id' for Indonesian accent, 'en' for default
            tts = gTTS(text=text, lang=lang, slow=False)
            tts.save(filepath)
        except Exception as e:
            print(f"Failed to generate audio for {author_id}: {e}")
            return ""
            
    return f"/audio/{filename}"

@app.get("/")
def read_root():
    return {"message": "Hello from Pinoyta Backend!"}

@app.get("/api/community-messages")
def get_community_messages(lang: str = "english") -> list[VoiceMessage]:
    """Fetch mock community messages generated by Mistral AI (or fallback)."""
    
    messages_data = []
    
    if MISTRAL_API_KEY:
        try:
            client = Mistral(api_key=MISTRAL_API_KEY)
            
            # Map frontend language to instruction
            lang_instruction = "English"
            if lang == "tagalog":
                lang_instruction = "Tagalog"
            elif lang == "bisaya":
                lang_instruction = "Cebuano/Bisaya"
            elif lang == "mamanwa":
                lang_instruction = "Minamanwa (or closely related Surigaonon/Bisaya)"
                
            prompt = f"""
            Generate 3 short, urgent community hazard reports from Lumad leaders during a severe typhoon in the Agusan-Surigao region, Philippines. 
            Format the output strictly as a JSON array of objects with the following keys:
            - author: The name of the leader (e.g., 'Elder Tano', 'Datu Makusog', 'Volunteer Aida').
            - role: Their title (e.g., 'IP Council Member', 'Tribal Chieftain', 'Health Worker').
            - transcript: A 1-2 sentence urgent report about floods, landslides, or evacuation (Must be written in {lang_instruction}).
            Return ONLY the JSON array, nothing else.
            """
            
            chat_response = client.chat.complete(
                model="mistral-small-latest",
                messages=[
                    {"role": "user", "content": prompt}
                ]
            )
            
            import json
            content = chat_response.choices[0].message.content
            # Strip potential markdown formatting if mistral wraps it
            if content.startswith("```json"):
                content = content.replace("```json", "").replace("```", "").strip()
            elif content.startswith("```"):
                content = content.replace("```", "").strip()
                
            raw_data = json.loads(content)
            
            # Add dynamic IDs and dialect simulations
            # Google TTS doesn't have native Bisaya/Mamanwa, so we use Tagalog (tl) for Philippine dialects and English (en) otherwise
            tts_lang_code = "en" if lang == "english" else "tl"
            
            for i, item in enumerate(raw_data):
                author_id = f"voice-{int(time.time())}-{i}"
                audio_url = generate_audio(item.get("transcript", ""), author_id, tts_lang_code)
                
                messages_data.append(VoiceMessage(
                    id=author_id,
                    author=item.get("author", "Leader"),
                    role=item.get("role", "Community Member"),
                    dialect="Minamanwa",
                    time=f"{random.randint(5, 50)} mins ago",
                    transcript=item.get("transcript", ""),
                    verified=True,
                    audioUrl=audio_url
                ))
            return messages_data
            
        except Exception as e:
            print(f"Mistral API Error: {e}")
            # Fallback to simulated below
    
    # Simulated Fallback (if no API key or Mistral fails)
    tts_lang_code = "en" if lang == "english" else "tl"
    
    fallbacks = {
        "english": [
            "The mountain streams are rising fast near the lower bend. Secure livestock now.",
            "Council advises all families near San Roque creek to assemble at the central shelter immediately.",
            "Medical supplies have arrived at the upper ridge. Please prioritize the elders and children."
        ],
        "tagalog": [
            "Mabilis na tumataas ang tubig sa ilog sa ibaba. Iseguro ang mga alagang hayop ngayon din.",
            "Pinapayuhan ng konseho ang lahat ng pamilya malapit sa sapa na magtipon sa evacuation center.",
            "Dumating na ang mga medical supplies sa itaas. Unahin ang mga matatanda at bata."
        ],
        "bisaya": [
            "Nagtubo na ug paspas ang tubig sa sapa sa ubos. Hiposa na ang mga baka ug kahoy.",
            "Nagtambag ang konseho nga ang tanang pamilya duol sa sapa magtigom sa sentral nga shelter.",
            "Naabot na ang mga tambal sa taas. Unaha ang mga tigulang ug mga bata."
        ],
        "mamanwa": [
            "Mataas ang suba ug kusog ang hangin. Pag-andam kamo sa pagbalhin sa taas nga dapit.",
            "Nagtambag ang konseho nga ang tanang pamilya duol sa sapa magtigom sa sentral nga shelter.",
            "Naabot na ang mga tambal sa taas. Unaha ang mga tigulang ug mga bata."
        ]
    }
    
    fallback_transcripts = fallbacks.get(lang, fallbacks["english"])
    
    simulated = [
        {
            "id": f"voice-1-fallback-{lang}",
            "author": "Elder Tano",
            "role": "IP Council Member",
            "dialect": "Minamanwa",
            "time": "15 mins ago",
            "transcript": fallback_transcripts[0],
            "verified": True,
            "lang": tts_lang_code
        },
        {
            "id": f"voice-2-fallback-{lang}",
            "author": "Datu Makusog",
            "role": "Tribal Chieftain",
            "dialect": "Minamanwa",
            "time": "40 mins ago",
            "transcript": fallback_transcripts[1],
            "verified": True,
            "lang": tts_lang_code
        },
        {
            "id": f"voice-3-fallback-{lang}",
            "author": "Health Worker Maria",
            "role": "Barangay Health Worker",
            "dialect": "Bisaya",
            "time": "1 hour ago",
            "transcript": fallback_transcripts[2],
            "verified": True,
            "lang": tts_lang_code
        }
    ]
    
    for item in simulated:
        audio_url = generate_audio(item["transcript"], item["id"], item.pop("lang"))
        item["audioUrl"] = audio_url
        messages_data.append(VoiceMessage(**item))
        
    return messages_data
